on:
  release:
    types: [published]

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Release name
        id: release_name
        run: echo '::set-output name=NAME::${{ github.ref }}' | sed 's/refs\/tags\/v//g'
      - name: Bump a version
        run: |
          sed -i 's/version": ".*"/version": "${{ steps.release_name.outputs.NAME }}"/g' composer.json
      - name: Commit a version
        uses: EndBug/add-and-commit@v5
        with:
          author_name: GitHub Actions
          author_email: bot@github.com
          message: "bump a version"
          add: "composer.json"
          branch: "master"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build project
        run: |
          zip -r knawat-module-dropshipping-${{ steps.release_name.outputs.NAME }}.zip ./ -x '.git/*' -x '.gitignore' -x 'vendor/*' -x '.github/*' -x '.vscode/*'
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./knawat-module-dropshipping-${{ steps.release_name.outputs.NAME }}.zip
          asset_name: knawat-module-dropshipping-${{ steps.release_name.outputs.NAME }}.zip
          asset_content_type: application/zip
